config/routes.rb
Rails.application.routes.draw do
 

get 'your_posts' => 'blog_posts#your_posts'
get 'user_profile' => 'blog_posts#user_profile'

  devise_for :users
  get 'comments/edit'

resources :blog_posts
resources :comments, only: [:edit, :create, :update, :destory]

  root 'blog_posts#index'

end

app/models/blog_post.rb
class BlogPost < ActiveRecord::Base
  has_many :comments 
  belongs_to :user
  
  validates :title, :blog_entry, presence: true
  validates :title, uniqueness: true, length: { maximum: 140 }
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :blog_post
  belongs_to :user

  validates :comment_entry, :blog_post_id, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

 has_many :blog_posts
 has_many :comments

 has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/default_image.png"
 validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :authenticate_user!

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :name, :birthday, :avatar])
     devise_parameter_sanitizer.permit(:account_update, keys: [:username, :name, :birthday, :avatar])

  end
end

app/controllers/blog_posts_controller.rb
class BlogPostsController < ApplicationController
before_action :set_blog_post, only: [:show, :edit, :update, :destory]

  def your_posts
  end 

  def user_profile
    @blog_posts = BlogPost.all
  end 

  def index
    @blog_posts = BlogPost.all 
  end

  def new
    @blog_post = BlogPost.new
  end

  def edit
  end

  def show
    @comment = Comment.new 
  end

  def create
    @blog_post = BlogPost.new(blog_post_params)

    respond_to do |format|
      if @blog_post.save
        format.html {redirect_to @blog_post, notice: "Blog post was created successfully."}
      else
          format.html {render :new}
      end
    end
  end

  def update
    respond_to do |format|
      if @blog_post.update(blog_post_params) 
          format.html {redirect_to @blog_post, notice: "Blog post was updated successfully."}
      else 
        format.html {render :edit}
      end 
    end
  end 

  def destroy
    @blog_post.destroy
    respond_to do |format|
      format.html {redirect_to blog_posts_url, notice: "Your blog post was DESTROYED!!!"}
    end
  end 
    

  private 

  def blog_post_params
    params.require(:blog_post).permit(:title, :blog_entry, :user_id)
  end

  def set_blog_post
    @blog_post = BlogPost.find(params[:id])
  end



end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:edit, :update, :destroy]

  def edit
  end

  def create 
    @comment = Comment.new(comment_params)

    respond_to do |format|
      if @comment.save
        format.html {redirect_to blog_post_path(id: @comment.blog_post_id), notice: "Comment was created successfully."}
      else
        format.html {redirect_to blog_post_path(id: @comment.blog_post_id), notice: "Comment failed to post"}
        end
    end
   end


  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html {redirect_to blog_post_path(id: @comment.blog_post_id), notice: "Comment was updated successfully."}
      else
        format.html {render :edit}
      end
    end
  end

  def destroy
    @comment.destroy
    respond_to do |format|
      format.html {redirect_to blog_post_path(id: @comment.blog_post_id), notice: "Your comment was DESTROYEDDDDDD!!!!"}
    end
    end

private

  def comment_params
    params.require(:comment).permit(:comment_entry, :blog_post_id, :user_id)
  end

  def set_comment
    @comment = Comment.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blog_posts_helper.rb
module BlogPostsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/controllers_helper.rb
module ControllersHelper
end

app/helpers/edit_helper.rb
module EditHelper
end

app/views/blog_posts/_form.html.erb
<%= form_for(@blog_post) do |f| %>
   <% if @blog_post.errors.any? %>
   <div class="error_explanation">
     <h2><%= pluralize(@blog_post.errors.count, "error") %> prohibited this blog post from being saved:</h2>

       <ul>
         <% @blog_post.errors.full_messages.each do |message| %>
         <li><%= message %></li>
         <% end %>
       </ul>

   </div>
   <% end %>

   <div class="form-group">
     <%= f.text_field :title, class: "form-control", placeholder: "Enter your cool blog post title here.." %>
   </div>
   <div class="form-group">
     <%= f.text_area :blog_entry, class: "form-control", rows: "12", placeholder: "Start typing away.." %>
   </div>
   <div class="form-group hidden">
     <%= f.number_field :user_id, value: current_user.id %>
   </div>
   <div class="actions">
     <%= f.submit "Post", class: "btn btn-warning" %>
   </div>
   <% end %>
    

app/views/blog_posts/edit.html.erb
<h1>Editing Blog Post</h1>

<div class="container">
  <%= render "form" %>
</div>
<br>

<%= link_to 'Back', @blog_post, class: "btn btn-primary" %> |
<%= link_to 'Home', blog_posts_path, class: "btn btn-primary" %>
<br>
<br>
<footer>
  <center><p>&copy 2016 JustBuiltIT Blog</p></center>
</footer>

app/views/blog_posts/index.html.erb
<h1>Welcome <%= current_user.name %></h1>

<div class="row">
   <% @blog_posts.each do |blog_post| %>
   <div class="col-md-6">
    <div class="panel panel-default">
      <div class="panel-heading">
         <%= blog_post.title %>
      </div>
      <div class="panel-body">
         <%= blog_post.user.username %>
         <%= image_tag current_user.avatar, :size => "20x20" %>
         <p><%= blog_post.blog_entry[0..250] %>... </p>
         <p><%= link_to 'show more', blog_post %></p>
         <p><%= blog_post.created_at.strftime(" created on: %b %d, %Y at %I:%M%p") %></p>
      </div>
      <div class="panel-footer">
      <% if current_user.id == blog_post.user.id %>
         <%= link_to 'Edit', edit_blog_post_path(blog_post), class: "btn btn-warning" %>
         <%= link_to 'Destroy', blog_post, method: :delete, data: {confirm: 'Are you sure?'}, class: "btn btn-danger" %>
         <% end %>
      </div>
    </div>
   </div>
   <% end %>
</div>

<br />
<%= link_to 'New Blog Post', new_blog_post_path, class: "btn btn-primary" %>
<br />
<br />
<footer>
  <center><p>&copy 2016 JustBuiltIT Blog</p></center>
</footer>

app/views/blog_posts/new.html.erb
<h1>Create a New Blog Post</h1>

<div class="container">
  <%= render "form" %>
</div>
<br>
<br>
<%= link_to "Back", blog_posts_path, class: "btn btn-primary" %>
<br>
<br>
<footer>
  <center><p>&copy 2016 JustBuiltIT Blog</p></center>
</footer>

app/views/blog_posts/show.html.erb
<p id="notice"><%= notice %></p>
<br>
<br>
<div class="panel panel-primary">
  <div class="panel-heading">
    <%= @blog_post.title %>
  </div>
  <div class="panel-body">
    <p>by <%= @blog_post.user.username %>
    <%= image_tag current_user.avatar, :size => "20x20" %></p>
    <p><%= @blog_post.blog_entry %></p>
    <p><%= time_ago_in_words(@blog_post.created_at) %> ago</p>

  </div>
</div>
<div class="panel panel-default">
  <div class="panel-heading">
    Comments
  </div>
  <div class="panel-body">
    <%= render @comment %>
  </div>
</div>

<div class="panel panel-success">
  <div class="panel-heading">
    Make a Comment
  </div>
  <div class="panel-body">
    <%= render 'comments/form' %> 
  </div>
</div>

<div>
  <%= link_to 'Edit', edit_blog_post_path(@blog_post), class: "btn btn-primary" %> |
  <%= link_to 'Back', blog_posts_path, class: "btn btn-primary" %>
</div>
<br>
<br>
<footer>
  <center><p>&copy 2016 JustBuiltIT Blog</p></center>
</footer>

app/views/blog_posts/user_profile.html.erb
<h1>Your profile</h1>
<br>

  <div class="profile">
    <%= image_tag current_user.avatar,  :size => "150x150" %></p>
    <p><strong>USERNAME:</strong> <%= current_user.username %></p>
    <p><strong>NAME:</strong> <%= current_user.name %></p>
    <p><strong>EMAIL:</strong> <%= current_user.email %></p>
    <p><strong>BIRTHDAY:</strong> <%= current_user.birthday %></p>
  </div>
  <br>
<%= link_to 'Edit Profile', edit_user_registration_path, class: "btn btn-warning" %>
<br>
<br>
<br>
<%= link_to 'Back', blog_posts_path, class: "btn btn-primary" %>
<br>
<br>  
<div class ="scroll">
<h1>Your Posts</h1>
<% current_user.blog_posts.each do |blog_post| %>
   <div class="col-md-16">
    <div class="panel panel-default">
      <div class="panel-heading">
         <%= blog_post.title %>
      </div>
      <div class="panel-body">
         <%= blog_post.user.username %><br />
         <p><%= blog_post.blog_entry[0..250] %>... </p>
         <p><%= link_to 'show more', blog_post %></p>
         <p><%= blog_post.created_at.strftime(" created on: %b %d, %Y at %I:%M%p") %></p>
      </div>
<% end %>
</div>
</div>
</div>

app/views/blog_posts/your_posts.html.erb
<% current_user.blog_posts.each do |blog_post| %>

   <div class="col-md-6">
    <div class="panel panel-default">
      <div class="panel-heading">
         <%= blog_post.title %>
      </div>
      <div class="panel-body">
         <%= blog_post.user.username %><br />
         <p><%= blog_post.blog_entry[0..250] %>... </p>
         <p><%= link_to 'show more', blog_post %></p>
         <p><%= blog_post.created_at.strftime(" created on: %b %d, %Y at %I:%M%p") %></p>
      </div>
      <div class="panel-footer">
         <%= link_to 'Edit', edit_blog_post_path(blog_post), class: "btn btn-warning" %>
         <%= link_to 'Destroy', blog_post, method: :delete, data: {confirm: 'Are you sure?'}, class: "btn btn-danger" %>
      </div>
    </div>
   </div>
   <% end %>

app/views/comments/_comment.html.erb
<% @blog_post.comments.each do |comment| %>

    <h4><%= comment.user.username %></h4>
    <p><%= comment.comment_entry %></p>
    <p><%= time_ago_in_words(comment.created_at) %></p>
    <p><%= link_to 'edit comment', edit_comment_path %></p>
  
  <% end %>
  <br>
  <br>

app/views/comments/_edit_comment_form.html.erb
<%= form_for(@comment) do |f| %>
   <% if @comment.errors.any? %>
   <div class="error_explanation">
     <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this blog post from being saved:</h2>

       <ul>
         <% @comment.errors.full_messages.each do |message| %>
         <li><%= message %></li>
         <% end %>
       </ul>

   </div>
   <% end %>

   <div class="form-group hidden">
     <%= f.number_field :user_id, value: current_user.id %>
   </div>
   <div class="form-group">
     <%= f.text_area :comment_entry, class: "form-control", rows: "3", placeholder: "Enter Comment here.." %>
   </div>
   <div class="form-group hidden">
   <%= f.number_field :comment_id, value: @comment.id %> 
   </div>
   <div class="actions">
     <%= f.submit "Comment", class: "btn btn-default" %>
   </div>
   <% end %>

app/views/comments/_form.html.erb
<%= form_for(@comment) do |f| %>
   <% if @comment.errors.any? %>
   <div class="error_explanation">
     <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this blog post from being saved:</h2>

       <ul>
         <% @comment.errors.full_messages.each do |message| %>
         <li><%= message %></li>
         <% end %>
       </ul>

   </div>
   <% end %>

   <div class="form-group">
     <%= f.text_area :comment_entry, class: "form-control", rows: "3", placeholder: "Enter Comment here.." %>
   </div>
   <div class="form-group hidden">
   <%= f.number_field :blog_post_id, value: @blog_post.id %> 
   </div>
   <div class="form-group hidden">
     <%= f.number_field :user_id, value: current_user.id %>
   </div>
   <div class="actions">
     <%= f.submit "Comment", class: "btn btn-default" %>
   </div>
   <% end %>

app/views/comments/edit.html.erb
<h1>Editing your Comment</h1>

<div class="container">
  <%= render "edit_comment_form" %>
</div>

<%= link_to 'Back', @blog_post %>
<%= link_to 'Home', blog_posts_path %>
<br>
<br>
<footer>
  <center><p>&copy 2016 JustBuiltIT Blog</p></center>
</footer>

app/views/controllers/edit.html.erb
<h1>Controllers#edit</h1>
<p>Find me in app/views/controllers/edit.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>JustBuildITBlog</title>
  <!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

<div class="jumbotron">
  <h1>JustBuildIT Blog</h1>
  <p>Where your ideas are shared with the universe!</p>
</div>


</head>
<body>

<div class="container">
<div class="pull-right">
  <% if user_signed_in? %>
  <%= link_to 'Home', blog_posts_path, class: "btn btn-primary" %>
  <%= link_to 'Your Profile', user_profile_path, class: "btn btn-primary" %>
  <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class: "btn btn-danger" %>
</div>
<% end %>
<%= yield %>
</div>

<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
</body>
</html>